spring:
  datasource:
   driver-class-name: org.h2.Driver
   username: sa
   password: 
   platform: org.hibernate.dialect.H2Dialect
   url: jdbc:h2:~/city;MODE=ORACLE;IGNORECASE=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE 
